
WITH CTE_CATEGORIES AS
(
    SELECT * FROM {{source('bronze' , 'Categories')}}
)
SELECT 
    CATEGORYID AS CATEGORY_ID,
    CATEGORYNAME AS CATEGORY_NAME,
    DESCRIPTION AS CATEGORY_DESCRIPTION
FROM CTE_CATEGORIES