{{
    config(materialized='view')
}}

WITH CTE_ORDERS AS 
(
    SELECT * FROM {{source('bronze' , 'Orders')}}
)
SELECT 
    ORDERID AS ORDER_ID,
    CUSTOMERID AS CUSTOMER_ID,
    ORDERDATE AS ORDER_DATE,
    REQUIREDDATE AS REQUIRED_DATE,
    SHIPPEDDATE AS SHIPPED_DATE,
    SHIPVIA AS SHIP_VIA,
    FREIGHT,
    SHIPNAME AS SHIP_NAME,
    SHIPADDRESS AS SHIP_ADDRESS ,
    SHIPCITY AS SHIP_CITY,
    SHIPREGION AS SHIP_REGION,
    SHIPPOSTALCODE AS SHIP_POSTALCODE,
    SHIPCOUNTRY AS SHIP_COUNTRY
FROM CTE_ORDERS