WITH CTE_ORDERS_DETAILS AS
(
    SELECT * FROM {{source('bronze' , 'Orders_details')}}
)
SELECT 
    ORDERID AS ORDER_ID,
    PRODUCTID AS PRODUCT_ID,
    UNITPRICE AS UNIT_PRICE,
    QUANTITY ,
    DISCOUNT 
FROM CTE_ORDERS_DETAILS