{{
    config(materialized='ephemeral')
}}

WITH CTE_CUSTOMERS AS 
(
    SELECT * FROM {{ref('Customers_2')}}
)
, CTE_CUSTOMERS_2 AS (
SELECT  
    CUSTOMERID,
    COMPANYNAME,
    CONTACTNAME,
    ADDRESS,
    CITY,
    REGION,
    POSTALCODE,
    COUNTRY,
    CASE 
        WHEN LENGTH(PHONE) = 9 THEN CONCAT('0' , PHONE)
        WHEN LENGTH(PHONE) = 8 THEN CONCAT('00' , PHONE)
        ELSE PHONE
    END AS PHONE,
    CASE 
        WHEN LENGTH(FAX) = 9 THEN CONCAT('0' , FAX)
        WHEN LENGTH(FAX) = 8 THEN CONCAT('00' , FAX)
        ELSE FAX
    END AS FAX
FROM CTE_CUSTOMERS
)
SELECT 
    CUSTOMERID,
    COMPANYNAME,
    CONTACTNAME,
    ADDRESS,
    CITY,
    REGION,
    POSTALCODE,
    COUNTRY,
    PHONE,
    FAX
FROM CTE_CUSTOMERS_2
WHERE LENGTH(PHONE) = 10 AND LENGTH(FAX) = 10