

WITH CTE_SHIP AS 
(
    SELECT * FROM {{ref('ship_lookup')}}
)
SELECT
    SHIP_ID,
    INITCAP(SHIP_NAME) AS SHIP_NAME,
    INITCAP(SHIP_ADDRESS) AS SHIP_ADDRESS,
    INITCAP(SHIP_CITY) AS SHIP_CITY,
    INITCAP(SHIP_REGION) AS SHIP_REGION,
    SHIP_POSTALCODE,
    INITCAP(SHIP_COUNTRY) AS SHIP_COUNTRY
FROM CTE_SHIP