{{config(materialized='view')}}

WITH CTE_SHIP AS 
(
    SELECT * FROM {{ref('ship')}}
),
CTE_SHIP_2 AS 
(
    SELECT ROW_NUMBER() OVER(PARTITION BY SHIP_NAME , SHIP_ADDRESS ORDER BY SHIP_NAME) AS SHIP_ORDER ,
        *
    FROM CTE_SHIP
), CTE_SHIP_3 AS 
(
    SELECT * FROM CTE_SHIP_2 
    WHERE SHIP_ORDER = 1
), CTE_SHIP_4 AS 
(
    SELECT ROW_NUMBER() OVER(ORDER BY SHIP_NAME) AS SHIP_ID ,  * FROM CTE_SHIP_3
)
SELECT  
        SHIP_ID , 
        SHIP_NAME,
        SHIP_ADDRESS,
        SHIP_CITY,
        SHIP_REGION,
        SHIP_POSTALCODE,
        SHIP_COUNTRY 
FROM CTE_SHIP_4