WITH CTE_ORDERS AS 
(
    SELECT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_DATE,
    REQUIRED_DATE,
    SHIPPED_DATE,
    SHIP_VIA,
    FREIGHT,
    SHIP_NAME AS ORDERS_SHIP_NAME,
    SHIP_ADDRESS AS ORDERS_SHIP_ADDRESS ,
    SHIP_CITY AS ORDERS_SHIP_CITY,
    SHIP_REGION AS ORDERS_SHIP_REGION,
    SHIP_POSTALCODE AS ORDERS_SHIP_POSTALCODE,
    SHIP_COUNTRY AS ORDERS_SHIP_COUNTRY
     FROM {{ref('Orders')}}
), CTE_SHIP_LOOKUP AS
(
    SELECT * FROM {{ref('ship_lookup')}}
) , CTE_ORDERS_2 AS (
SELECT * FROM CTE_ORDERS O
LEFT JOIN CTE_SHIP_LOOKUP L 
ON O.ORDERS_SHIP_NAME = L.SHIP_NAME 
AND O.ORDERS_SHIP_ADDRESS = L.SHIP_ADDRESS 
) 
SELECT 
    ORDER_ID,
    CUSTOMER_ID,
    SHIP_ID,
    ORDER_DATE,
    REQUIRED_DATE,
    SHIPPED_DATE,
    SHIP_VIA,
    FREIGHT

FROM CTE_ORDERS_2