{{
    config(
        materialized='table',
        alias='FactOrders'
    )
}}

WITH CTE_ORDERS_DETAILS AS 
(
    SELECT 
    ORDER_ID AS OD_ORDER_ID,
    PRODUCT_ID AS OD_PRODUCT_ID,
    UNIT_PRICE AS OD_UNIT_PRICE,
    QUANTITY AS OD_QUANTITY,
    DISCOUNT AS OD_DISCOUNT
    FROM {{ref('Orders_details')}}
),
CTE_ORDERS AS 
(
    SELECT * FROM {{ref('Orders_2')}}
)
SELECT 
    ORDER_ID ,
    CUSTOMER_ID ,
    SHIP_ID,
    OD_PRODUCT_ID AS PRODUCT_ID,
    OD_UNIT_PRICE AS UNIT_PRICE,
    OD_QUANTITY AS QUANTITY,
    OD_DISCOUNT AS DISCOUNT,
    CAST(ORDER_DATE AS DATE)    AS    ORDER_DATE,
    CAST(REQUIRED_DATE AS DATE) AS    REQUIRED_DATE,
    CAST(SHIPPED_DATE AS DATE)  AS    SHIPPED_DATE,
    SHIP_VIA,
    FREIGHT
FROM CTE_ORDERS_DETAILS OD 
LEFT JOIN CTE_ORDERS O 
ON O.ORDER_ID = OD.OD_ORDER_ID
